### ISSUE TITLE
Docker container incompatible with new linux device driver naming.

### ISSUE THREAD

**Issue by tokenativo** [Blockstream/bitcoinsatellite#7]
New versions of TBS drivers consider /dev/dvb/adapterX naming, incompatible with dvb0_0 device name.

Kernel: Linux 5.4.0-1045-raspi aarch64

Device: TBS5927

Driver compiled according support on issue: https://github.com/tbsdtv/linux_media/issues/261
media_build branch extra substituted .blocksat/src/tbsdriver/media_build
.blocksat/src/tbsdriver/media_build/install.sh used to compile and install the driver.

bitcoin satellite core RUNNING PROPERLY outside the containers, but when trying to run on docker containers:

inspired by the commands on https://github.com/Blockstream/satellite/blob/master/doc/docker.md
for USB Receiver

Had to change the device name from /dev/dvb0_0 to /dev/dvb/adapter0 on the Docker run command, the Docker went up but does not reconize the device properly.

```
user@oasis:~$ sudo docker run -it     --device=/dev/dvb/adapter0  --cap-add=NET_ADMIN     --cap-add=SYS_ADMIN     -v /home/user/.blocksat:/root/.blocksat/  -v /home/user/bitcoin:/root/.bitcoin/   --restart=unless-stopped  blockstream/satellite
root@ddeb93818f6e:/# bitcoind
2021-11-17T06:14:00Z Bitcoin Core version v22.0.0 (release build)
2021-11-17T06:14:00Z Bitcoin Satellite version v0.2.3 (release build)
2021-11-17T06:14:00Z InitParameterInteraction: parameter interaction: -proxy set -> setting -upnp=0
2021-11-17T06:14:00Z InitParameterInteraction: parameter interaction: -proxy set -> setting -natpmp=0
2021-11-17T06:14:00Z InitParameterInteraction: parameter interaction: -proxy set -> setting -discover=0
2021-11-17T06:14:00Z Assuming ancestors of block 00000000000000000008a89e854d57e5667df88f1cdef6fde2fbca1de5b639ad have valid signatures.
2021-11-17T06:14:00Z Setting nMinimumChainWork=00000000000000000000000000000000000000001fa4663bbbe19f82de910280
2021-11-17T06:14:00Z Using the 'standard' SHA256 implementation
2021-11-17T06:14:01Z Default data directory /root/.bitcoin
2021-11-17T06:14:01Z Using data directory /root/.bitcoin
2021-11-17T06:14:01Z Config file: /root/.bitcoin/bitcoin.conf
2021-11-17T06:14:01Z Config file arg: bind="10.21.21.8"
2021-11-17T06:14:01Z Config file arg: blockfilterindex="1"
2021-11-17T06:14:01Z Config file arg: dbcache="200"
2021-11-17T06:14:01Z Config file arg: debug="udpnet"
2021-11-17T06:14:01Z Config file arg: debug="udpmulticast"
2021-11-17T06:14:01Z Config file arg: deprecatedrpc="addresses"
2021-11-17T06:14:01Z Config file arg: listen="1"
2021-11-17T06:14:01Z Config file arg: maxmempool="300"
2021-11-17T06:14:01Z Config file arg: peerblockfilters="1"
2021-11-17T06:14:01Z Config file arg: peerbloomfilters="1"
2021-11-17T06:14:01Z Config file arg: port="8333"
2021-11-17T06:14:01Z Config file arg: proxy="10.21.21.11:9050"
2021-11-17T06:14:01Z Config file arg: rpcallowip="10.21.21.1/16"
2021-11-17T06:14:01Z Config file arg: rpcallowip="127.0.0.1"
2021-11-17T06:14:01Z Config file arg: rpcauth=****
2021-11-17T06:14:01Z Config file arg: rpcbind=****
2021-11-17T06:14:01Z Config file arg: rpcbind=****
2021-11-17T06:14:01Z Config file arg: rpcport="8332"
2021-11-17T06:14:01Z Config file arg: rpcworkqueue="64"
2021-11-17T06:14:01Z Config file arg: txindex="1"
2021-11-17T06:14:01Z Config file arg: udpmulticast="dvb0_0,239.0.0.2:4434,172.16.235.9,1,blocksat-tbs"
2021-11-17T06:14:01Z Config file arg: udpmulticastloginterval="600"
2021-11-17T06:14:01Z Config file arg: zmqpubhashblock="tcp://0.0.0.0:28334"
2021-11-17T06:14:01Z Config file arg: zmqpubrawblock="tcp://0.0.0.0:28332"
2021-11-17T06:14:01Z Config file arg: zmqpubrawtx="tcp://0.0.0.0:28333"
2021-11-17T06:14:01Z Using at most 125 automatic connections (1048576 file descriptors available)
2021-11-17T06:14:01Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
2021-11-17T06:14:01Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
2021-11-17T06:14:01Z Script verification uses 3 additional threads
2021-11-17T06:14:01Z scheduler thread start
2021-11-17T06:14:01Z Binding RPC on address 10.21.21.8 port 8332 failed.
2021-11-17T06:14:01Z HTTP: creating work queue of depth 64
2021-11-17T06:14:01Z Using random cookie authentication.
2021-11-17T06:14:01Z Generated RPC authentication cookie /root/.bitcoin/.cookie
2021-11-17T06:14:01Z Using rpcauth authentication.
2021-11-17T06:14:01Z HTTP: starting 4 worker threads
2021-11-17T06:14:01Z Using wallet directory /root/.bitcoin
2021-11-17T06:14:01Z init message: Verifying wallet(s)…
2021-11-17T06:14:01Z init message: Loading banlist…
2021-11-17T06:14:01Z SetNetworkActive: true
2021-11-17T06:14:01Z Using /16 prefix for IP bucketing
2021-11-17T06:14:01Z Cache configuration:
2021-11-17T06:14:01Z * Using 2.0 MiB for block index database
2021-11-17T06:14:01Z * Using 24.8 MiB for transaction index database
2021-11-17T06:14:01Z * Using 21.7 MiB for basic block filter index database
2021-11-17T06:14:01Z * Using 8.0 MiB for chain state database
2021-11-17T06:14:01Z * Using 143.6 MiB for in-memory UTXO set (plus up to 286.1 MiB of unused mempool space)
2021-11-17T06:14:01Z init message: Loading block index…
2021-11-17T06:14:01Z Switching active chainstate to Chainstate [ibd] @ height -1 (null)
2021-11-17T06:14:01Z Opening LevelDB in /root/.bitcoin/blocks/index
2021-11-17T06:14:01Z Opened LevelDB successfully
2021-11-17T06:14:01Z Using obfuscation key for /root/.bitcoin/blocks/index: 0000000000000000
2021-11-17T06:14:22Z LoadBlockIndexDB: last block file = 2808
2021-11-17T06:14:22Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=36, size=42422373, heights=710044...710079, time=2021-11-16...2021-11-17)
2021-11-17T06:14:22Z Checking all blk files are present...
2021-11-17T06:14:23Z Opening LevelDB in /root/.bitcoin/chainstate
2021-11-17T06:14:23Z Opened LevelDB successfully
2021-11-17T06:14:23Z Using obfuscation key for /root/.bitcoin/chainstate: eea31e6916722d15
2021-11-17T06:14:24Z Loaded best chain: hashBestChain=00000000000000000003c33222688c5eb8ce01c8a13af089710d35dd64e0b999 height=710079 date=2021-11-17T04:56:51Z progress=0.999984
2021-11-17T06:14:24Z init message: Verifying blocks…
2021-11-17T06:14:24Z Verifying last 6 blocks at level 3
2021-11-17T06:14:24Z [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
2021-11-17T06:14:29Z No coin database inconsistencies in last 6 blocks (6125 transactions)
2021-11-17T06:14:29Z  block index           27887ms
2021-11-17T06:14:29Z Opening LevelDB in /root/.bitcoin/future_blocks
2021-11-17T06:14:29Z Opened LevelDB successfully
2021-11-17T06:14:29Z Using obfuscation key for /root/.bitcoin/future_blocks: 0000000000000000
2021-11-17T06:14:29Z Opening LevelDB in /root/.bitcoin/indexes/txindex
2021-11-17T06:14:30Z Opened LevelDB successfully
2021-11-17T06:14:30Z Using obfuscation key for /root/.bitcoin/indexes/txindex: 0000000000000000
2021-11-17T06:14:30Z txindex thread start
2021-11-17T06:14:30Z txindex is enabled at height 710079
2021-11-17T06:14:30Z txindex thread exit
2021-11-17T06:14:30Z Opening LevelDB in /root/.bitcoin/indexes/blockfilter/basic/db
2021-11-17T06:14:30Z Opened LevelDB successfully
2021-11-17T06:14:30Z Using obfuscation key for /root/.bitcoin/indexes/blockfilter/basic/db: 0000000000000000
2021-11-17T06:14:30Z block tree size = 710080
2021-11-17T06:14:30Z nBestHeight = 710079
2021-11-17T06:14:30Z Unable to bind to 10.21.21.8:8333 on this computer (bind returned error Cannot assign requested address (99))
2021-11-17T06:14:30Z Error: Unable to bind to 10.21.21.8:8333 on this computer (bind returned error Cannot assign requested address (99))
Error: 2021-11-17T06:14:30Z loadblk thread start
Unable to bind to 10.21.21.8:8333 on this computer (bind returned error Cannot assign requested address (99))
2021-11-17T06:14:30Z Leaving InitialBlockDownload (latching to false)
2021-11-17T06:14:30Z Bound to 127.0.0.1:8334
2021-11-17T06:14:30Z init message: Loading P2P addresses…
2021-11-17T06:14:30Z basic block filter index thread start
2021-11-17T06:14:30Z basic block filter index is enabled at height 710079
2021-11-17T06:14:30Z basic block filter index thread exit
2021-11-17T06:14:30Z torcontrol thread start
2021-11-17T06:14:31Z Loaded 64463 addresses from peers.dat  918ms
2021-11-17T06:14:31Z Loaded 0 addresses from "anchors.dat"
2021-11-17T06:14:31Z 0 block-relay-only anchors will be tried for connections.
2021-11-17T06:14:31Z init message: Starting network threads…
2021-11-17T06:14:31Z addcon thread start
2021-11-17T06:14:31Z opencon thread start
2021-11-17T06:14:31Z msghand thread start
2021-11-17T06:14:31Z net thread start
2021-11-17T06:14:31Z dnsseed thread start
2021-11-17T06:14:31Z Waiting 300 seconds before querying DNS seeds.
2021-11-17T06:14:31Z Error: couldn't find an index for interface dvb0_0: No such device
2021-11-17T06:14:31Z Error: Failed to initialize UDP connections
Error: Failed to initialize UDP connections
2021-11-17T06:14:31Z tor: Thread interrupt
2021-11-17T06:14:31Z torcontrol thread exit
2021-11-17T06:14:31Z addcon thread exit
2021-11-17T06:14:31Z opencon thread exit
2021-11-17T06:14:31Z dnsseed thread exit
2021-11-17T06:14:31Z Shutdown: In progress...
2021-11-17T06:14:31Z net thread exit
2021-11-17T06:14:31Z msghand thread exit
2021-11-17T06:14:32Z DumpAnchors: Flush 0 outbound block-relay-only peer addresses to anchors.dat started
2021-11-17T06:14:32Z DumpAnchors: Flush 0 outbound block-relay-only peer addresses to anchors.dat completed (0.02s)
2021-11-17T06:14:32Z scheduler thread exit
2021-11-17T06:14:34Z Imported mempool transactions from disk: 731 succeeded, 0 failed, 0 expired, 0 already there, 0 waiting for initial broadcast
2021-11-17T06:14:34Z loadblk thread exit
2021-11-17T06:14:34Z Writing 0 unbroadcast transactions to disk.
2021-11-17T06:14:34Z Dumped mempool: 0.016371s to copy, 0.039826s to dump
2021-11-17T06:14:34Z FlushStateToDisk: write coins cache to disk (2491 coins, 365kB) started
2021-11-17T06:14:34Z FlushStateToDisk: write coins cache to disk (2491 coins, 365kB) completed (0.00s)
2021-11-17T06:14:34Z FlushStateToDisk: write coins cache to disk (0 coins, 40kB) started
2021-11-17T06:14:34Z FlushStateToDisk: write coins cache to disk (0 coins, 40kB) completed (0.00s)
2021-11-17T06:14:37Z Shutdown: done
root@ddeb93818f6e:/#

```

Tried also to run bitcoin satellite node to run with the device configuration of the host, but was unable to connect to the device, according to the log:

```
root@56c11a1d9af9:/# bitcoind
2021-11-17T05:36:32Z Bitcoin Core version v22.0.0 (release build)
2021-11-17T05:36:32Z Bitcoin Satellite version v0.2.3 (release build)
2021-11-17T05:36:32Z Assuming ancestors of block 00000000000000000008a89e854d57e5667df88f1cdef6fde2fbca1de5b639ad have valid signatures.
2021-11-17T05:36:32Z Setting nMinimumChainWork=00000000000000000000000000000000000000001fa4663bbbe19f82de910280
2021-11-17T05:36:32Z Using the 'standard' SHA256 implementation
2021-11-17T05:36:32Z Default data directory /root/.bitcoin
2021-11-17T05:36:32Z Using data directory /root/.bitcoin
2021-11-17T05:36:32Z Config file: /root/.bitcoin/bitcoin.conf
2021-11-17T05:36:32Z Config file arg: debug="udpnet"
2021-11-17T05:36:32Z Config file arg: debug="udpmulticast"
2021-11-17T05:36:32Z Config file arg: udpmulticast="dvb0_0,239.0.0.2:4434,172.16.235.9,1,blocksat-tbs"
2021-11-17T05:36:32Z Config file arg: udpmulticastloginterval="600"
2021-11-17T05:36:32Z Using at most 125 automatic connections (1048576 file descriptors available)
2021-11-17T05:36:32Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
2021-11-17T05:36:32Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
2021-11-17T05:36:32Z Script verification uses 3 additional threads
2021-11-17T05:36:32Z scheduler thread start
2021-11-17T05:36:32Z libevent: getaddrinfo: address family for nodename not supported
2021-11-17T05:36:32Z Binding RPC on address ::1 port 8332 failed.
2021-11-17T05:36:32Z HTTP: creating work queue of depth 16
2021-11-17T05:36:32Z Using random cookie authentication.
2021-11-17T05:36:32Z Generated RPC authentication cookie /root/.bitcoin/.cookie
2021-11-17T05:36:32Z HTTP: starting 4 worker threads
2021-11-17T05:36:32Z Using wallet directory /root/.bitcoin
2021-11-17T05:36:32Z init message: Verifying wallet(s)…
2021-11-17T05:36:32Z init message: Loading banlist…
2021-11-17T05:36:32Z SetNetworkActive: true
2021-11-17T05:36:32Z Using /16 prefix for IP bucketing
2021-11-17T05:36:32Z Cache configuration:
2021-11-17T05:36:32Z * Using 2.0 MiB for block index database
2021-11-17T05:36:32Z * Using 8.0 MiB for chain state database
2021-11-17T05:36:32Z * Using 440.0 MiB for in-memory UTXO set (plus up to 286.1 MiB of unused mempool space)
2021-11-17T05:36:32Z init message: Loading block index…
2021-11-17T05:36:32Z Switching active chainstate to Chainstate [ibd] @ height -1 (null)
2021-11-17T05:36:32Z Opening LevelDB in /root/.bitcoin/blocks/index
2021-11-17T05:36:32Z Opened LevelDB successfully
2021-11-17T05:36:32Z Using obfuscation key for /root/.bitcoin/blocks/index: 0000000000000000
2021-11-17T05:36:54Z LoadBlockIndexDB: last block file = 2808
2021-11-17T05:36:54Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=36, size=42422373, heights=710044...710079, time=2021-11-16...2021-11-17)
2021-11-17T05:36:54Z Checking all blk files are present...
2021-11-17T05:36:55Z Opening LevelDB in /root/.bitcoin/chainstate
2021-11-17T05:36:55Z Opened LevelDB successfully
2021-11-17T05:36:55Z Using obfuscation key for /root/.bitcoin/chainstate: eea31e6916722d15
2021-11-17T05:36:56Z Loaded best chain: hashBestChain=00000000000000000003c33222688c5eb8ce01c8a13af089710d35dd64e0b999 height=710079 date=2021-11-17T04:56:51Z progress=0.999992
2021-11-17T05:36:56Z init message: Verifying blocks…
2021-11-17T05:36:56Z Verifying last 6 blocks at level 3
2021-11-17T05:36:56Z [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
2021-11-17T05:36:59Z No coin database inconsistencies in last 6 blocks (6125 transactions)
2021-11-17T05:36:59Z  block index           27213ms
2021-11-17T05:36:59Z Opening LevelDB in /root/.bitcoin/future_blocks
2021-11-17T05:36:59Z Opened LevelDB successfully
2021-11-17T05:36:59Z Using obfuscation key for /root/.bitcoin/future_blocks: 0000000000000000
2021-11-17T05:36:59Z block tree size = 710080
2021-11-17T05:36:59Z nBestHeight = 710079
2021-11-17T05:36:59Z Bound to 127.0.0.1:8334
2021-11-17T05:36:59Z loadblk thread start
2021-11-17T05:36:59Z Bound to [::]:8333
2021-11-17T05:36:59Z Bound to 0.0.0.0:8333
2021-11-17T05:36:59Z init message: Loading P2P addresses…
2021-11-17T05:36:59Z torcontrol thread start
2021-11-17T05:36:59Z Leaving InitialBlockDownload (latching to false)
2021-11-17T05:37:02Z Loaded 64463 addresses from peers.dat  2409ms
2021-11-17T05:37:02Z Loaded 0 addresses from "anchors.dat"
2021-11-17T05:37:02Z 0 block-relay-only anchors will be tried for connections.
2021-11-17T05:37:02Z init message: Starting network threads…
2021-11-17T05:37:02Z net thread start
2021-11-17T05:37:02Z dnsseed thread start
2021-11-17T05:37:02Z Waiting 300 seconds before querying DNS seeds.
2021-11-17T05:37:02Z addcon thread start
2021-11-17T05:37:02Z opencon thread start
2021-11-17T05:37:02Z msghand thread start
2021-11-17T05:37:02Z Error: couldn't find an index for interface dvb0_0: No such device
2021-11-17T05:37:02Z Error: Failed to initialize UDP connections
Error: Failed to initialize UDP connections
2021-11-17T05:37:02Z tor: Thread interrupt
2021-11-17T05:37:02Z Shutdown: In progress...
2021-11-17T05:37:02Z torcontrol thread exit
2021-11-17T05:37:02Z opencon thread exit
2021-11-17T05:37:02Z addcon thread exit
2021-11-17T05:37:02Z dnsseed thread exit
2021-11-17T05:37:02Z net thread exit
2021-11-17T05:37:02Z msghand thread exit
2021-11-17T05:37:03Z DumpAnchors: Flush 0 outbound block-relay-only peer addresses to anchors.dat started
2021-11-17T05:37:03Z DumpAnchors: Flush 0 outbound block-relay-only peer addresses to anchors.dat completed (0.01s)
2021-11-17T05:37:03Z scheduler thread exit
2021-11-17T05:37:05Z Imported mempool transactions from disk: 731 succeeded, 0 failed, 0 expired, 0 already there, 0 waiting for initial broadcast
2021-11-17T05:37:06Z loadblk thread exit
2021-11-17T05:37:06Z Writing 0 unbroadcast transactions to disk.
2021-11-17T05:37:06Z Dumped mempool: 0.006228s to copy, 0.033123s to dump
2021-11-17T05:37:06Z FlushStateToDisk: write coins cache to disk (2491 coins, 365kB) started
2021-11-17T05:37:06Z FlushStateToDisk: write coins cache to disk (2491 coins, 365kB) completed (0.00s)
2021-11-17T05:37:06Z FlushStateToDisk: write coins cache to disk (0 coins, 40kB) started
2021-11-17T05:37:06Z FlushStateToDisk: write coins cache to disk (0 coins, 40kB) completed (0.00s)
2021-11-17T05:37:08Z Shutdown: done
```

**Comment by blockstreamsatellite** [comment]
Hi @tokenativo ,

Thanks for posting the issue.

> Had to change the device name from /dev/dvb0_0 to /dev/dvb/adapter0 

Thanks for catching the typo on the instructions. They are updated now. 

Also, note the device has always been named as `/dev/dvb/adapterX`, so this is not due to the driver version. The device path is `/dev/dvb/adapterX`, whereas the corresponding network interface is named `dvbX_Y`, where `X` is the adapter number (same as in the device path) and `Y` is the frontend number (zero in the current setup). The confusion on the Docker instructions was between the device and network interface names.

Regarding the error, on your first attempt, I see the following error log:

```
2021-11-17T06:14:30Z Error: Unable to bind to 10.21.21.8:8333 on this computer (bind returned error Cannot assign requested address (99))
Error: 2021-11-17T06:14:30Z loadblk thread start
Unable to bind to 10.21.21.8:8333 on this computer (bind returned error Cannot assign requested address (99))
```

That's probably because you didn't run the docker container with option `--network=host`. Try that and see if it works. Alternatively, it could also be a problem with another bitcoind instance already running on this machine, in which case you would need to specify other ports with the `-port`/`-rpcport` bitcoind options. However, I think it's more likely to be an issue with the missing `--network=host` argument on the `docker run` command.

> Tried also to run bitcoin satellite node to run with the device configuration of the host, 

Not sure what you mean by that. Which command you used to launch the Docker container in the second attempt? 

When you are inside the container, you can check if the `dvb0_0` interface is available by running a command like the following:

```
ip link show | grep dvb
```

It seems the problem on your second attempt was not finding the interface. Again, you can only see the host interfaces inside the container by running the container with the `--network=host` option.

Lastly, I'm not sure if you ran the `blocksat-cli usb config` command outside the container or inside the container. Both options would work. However, inside the container, you would need a patch we've pushed just now. Let me know if that's the case and I can send further instructions. Or just run the configuration step outside the container for now.

**Comment by tokenativo** [comment]
> Let me know if that's the case and I can send further instructions. Or just run the configuration step outside the container for now.

I was running outside, but since I was able to start the container, I would like to run inside, just run into the problem:

`# blocksat-cli usb config

------------------------------- Find DVB Adapter -------------------------------
ERROR    FE_SET_VOLTAGE: Operation not permitted
Found DVB-S2 adapter: TurboSight TBS 5927

--------------------------- Find dvbnet interface(s) ---------------------------

------------------------------ Network Interface ------------------------------
Network interface dvb0_0 already exists
Network interface dvb0_0 already configured correctly

----------------------------- Reverse Path Filters -----------------------------
It will be necessary to reconfigure some reverse path (RP) filtering
rules applied by the Linux kernel. This is required to prevent the
filtering of the one-way Blockstream Satellite traffic.

OK to proceed? [Y/n]
RP filter is already enabled on interface br-27f89e1fc30d
RP filter is already enabled on interface br-481a203de6cb
RP filter is already enabled on interface br-9888f63697b4
RP filter is already enabled on interface br-b2eedc3ff343
RP filter is already enabled on interface default
RP filter is already enabled on interface docker0
RP filter is already enabled on interface eth0
RP filter is already enabled on interface veth00de7d5
RP filter is already enabled on interface veth0a0a3e0
RP filter is already enabled on interface veth19c3822
RP filter is already enabled on interface veth1b13d8f
RP filter is already enabled on interface veth20c61ba
RP filter is already enabled on interface veth3d536e5
RP filter is already enabled on interface veth4016a81
RP filter is already enabled on interface veth4d29f19
RP filter is already enabled on interface veth558bafd
RP filter is already enabled on interface veth5a190bd
RP filter is already enabled on interface veth5ef7692
RP filter is already enabled on interface veth613c2f4
RP filter is already enabled on interface veth61f355e
RP filter is already enabled on interface veth6bd0586
RP filter is already enabled on interface veth7ee1e68
RP filter is already enabled on interface veth97a91ed
RP filter is already enabled on interface vethba8ec55
RP filter is already enabled on interface vethd84b298
RP filter is already enabled on interface vethf60b7f7
RP filter is already enabled on interface vethfdd6e05
RP filter is already enabled on interface wlan0
Disabling the RP filter on interface "all"
sysctl: setting key "net.ipv4.conf.all.rp_filter", ignoring: Read-only file system
Disabling the RP filter on interface "dvb0_0"
sysctl: setting key "net.ipv4.conf.dvb0_0.rp_filter", ignoring: Read-only file system

-------------------------------- Firewall Rules --------------------------------
A firewall rule is required to accept Blocksat traffic arriving
through interface dvb0_0 towards UDP ports 4433,4434.


Firewall rule already configured

Chain INPUT (policy ACCEPT 1045 packets, 84467 bytes)
num   pkts bytes target     prot opt in     out     source               destination
1 0 0 ACCEPT udp -- dvb0_0 any anywhere anywhere multiport dports 4433,4434

Skipping...

----------------------------- Interface IP Address -----------------------------
Traceback (most recent call last):
  File "/usr/local/bin/blocksat-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/blocksatcli/main.py", line 81, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/blocksatcli/usb.py", line 689, in usb_config
    ip.set_ips(net_ifs, ips, dry=runner.dry)
  File "/usr/local/lib/python3.8/dist-packages/blocksatcli/ip.py", line 224, in set_ips
    _set_ip(net_if, ip_addr, verbose)
  File "/usr/local/lib/python3.8/dist-packages/blocksatcli/ip.py", line 198, in _set_ip
    _set_static_iface_ip(net_if, inet_if)
  File "/usr/local/lib/python3.8/dist-packages/blocksatcli/ip.py", line 141, in _set_static_iface_ip
    raise ValueError("Could not set a static IP address on interface "
ValueError: Could not set a static IP address on interface dvb0_0
`

**Comment by blockstreamsatellite** [comment]
Hi @tokenativo ,

So, you need the latest version from the [Github repository](https://github.com/Blockstream/satellite) to run the `usb config` command inside the container. This version is not released yet (coming soon), so you would need to build the container from source, as follows:

First, remove your current container image(s) downloaded from Docker Hub to avoid confusion:
```
docker rmi blockstream/satellite:0.4.1 blockstream/satellite:latest
```

Next, clone the source-code repository:
```
git clone https://github.com/Blockstream/satellite.git
cd satellite/
```

Then, run the following command to rebuild the Docker image:
```
make docker
```

Finally, rerun the container and try the `usb config` command.

Let us know how it goes.
